/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedReportRouteImport } from './routes/(authenticated)/report'
import { Route as authenticatedCheck_attendanceRouteImport } from './routes/(authenticated)/check_attendance'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedReportRoute = authenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedCheck_attendanceRoute =
  authenticatedCheck_attendanceRouteImport.update({
    id: '/check_attendance',
    path: '/check_attendance',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check_attendance': typeof authenticatedCheck_attendanceRoute
  '/report': typeof authenticatedReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check_attendance': typeof authenticatedCheck_attendanceRoute
  '/report': typeof authenticatedReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/check_attendance': typeof authenticatedCheck_attendanceRoute
  '/(authenticated)/report': typeof authenticatedReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/check_attendance' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/check_attendance' | '/report'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(authenticated)/check_attendance'
    | '/(authenticated)/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/report': {
      id: '/(authenticated)/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof authenticatedReportRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/check_attendance': {
      id: '/(authenticated)/check_attendance'
      path: '/check_attendance'
      fullPath: '/check_attendance'
      preLoaderRoute: typeof authenticatedCheck_attendanceRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedCheck_attendanceRoute: typeof authenticatedCheck_attendanceRoute
  authenticatedReportRoute: typeof authenticatedReportRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedCheck_attendanceRoute: authenticatedCheck_attendanceRoute,
  authenticatedReportRoute: authenticatedReportRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
